### PR TITLE
Switch to golangci-lint

### PR DESCRIPTION
**Pull request by ptman**
Which go version should be targeted? Is 1.12 even supported anymore?

### CODE REVIEW

**Comment by ptman** [comment]
#59

**Comment by ptman** [comment]
What should be done about lint errors? //nolint? fix them?

**Comment by neilalexander** [comment]
It's best to fix the lint errors if you don't mind.

**Comment by ptman** [comment]
Better?

**Comment by ptman** [comment]
@neilalexander PTAL

**Comment by ptman** [comment]
@neilalexander PTAL

**Comment by ptman** [comment]
or @Kegsay / @t3chguy

**Comment by neilalexander** [comment]
Generally looks fine - we do require Go 1.13 now though and I think our `gocyclo` limit is 13. Happy to merge once those tweaks are made.

**Comment by Kegsay** [comment]
LGTM

**Comment by marco-m** [comment]
ping ?

**Comment by ptman** [comment]
oh, new conflicts, I'll have a look tomorrow, but please merge it then before new conflicts appear

**Comment by ptman** [comment]
Oh, @neilalexander  already did this in #78 ?

**Comment by neilalexander** [comment]
Ah, yes, I forgot about this PR and was prompted to do it the other day after speaking to someone.

**Comment by neilalexander** [comment]
Closing since already done - thanks for looking into this though / for the reminder.

**Pull request closed without merging**
